-- Octo: GitHub PR and issue review from within Neovim
return {
  'pwntester/octo.nvim',
  dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-telescope/telescope.nvim',
    'nvim-tree/nvim-web-devicons',
  },
  cmd = { 'Octo' },
  keys = {
    { '<leader>oo', '<cmd>Octo actions<cr>', desc = '[O]cto actions menu' },
    { '<leader>op', '<cmd>Octo pr list<cr>', desc = '[O]cto [P]R list' },
    { '<leader>oP', '<cmd>Octo pr changes<cr>', desc = '[O]cto [P]R changes (all files)' },
    { '<leader>oi', '<cmd>Octo issue list<cr>', desc = '[O]cto [I]ssue list' },
    { '<leader>or', '<cmd>Octo review start<cr>', desc = '[O]cto start [R]eview' },
    { '<leader>oc', '<cmd>Octo review submit<cr>', desc = '[O]cto submit [C]omment' },
    { '<leader>oa', '<cmd>Octo review approve<cr>', desc = '[O]cto [A]pprove PR' },
    { '<leader>od', '<cmd>Octo review discard<cr>', desc = '[O]cto [D]iscard review' },
    { '<leader>oq', '<cmd>Octo review close<cr>', desc = '[O]cto review [Q]uit' },
    { '<leader>ob', '<cmd>Octo pr browser<cr>', desc = '[O]cto open in [B]rowser' },
  },
  config = function(_, opts)
    require('octo').setup(opts)
  end,
  opts = {
    default_remote = { 'upstream', 'origin' },
    enable_builtin = false,
    use_timeline = true,
    use_diagnostic_signs = true,
    ui = {
      use_signcolumn = true,
    },
    issues = {
      order_by = {
        field = 'CREATED_AT',
        direction = 'DESC',
      },
    },
    pull_requests = {
      order_by = {
        field = 'CREATED_AT',
        direction = 'DESC',
      },
      always_select_remote_on_create = false,
    },
    file_panel = {
      size = 10,
      use_icons = true,
    },
    mappings = {
      issue = {
        close_issue = { lhs = '<leader>ic', desc = 'close issue' },
        reopen_issue = { lhs = '<leader>io', desc = 'reopen issue' },
        list_issues = { lhs = '<leader>il', desc = 'list open issues on same repo' },
        reload = { lhs = '<C-r>', desc = 'reload issue' },
        open_in_browser = { lhs = '<C-b>', desc = 'open issue in browser' },
        copy_url = { lhs = '<C-y>', desc = 'copy url to system clipboard' },
        add_assignee = { lhs = '<leader>iaa', desc = 'add assignee' },
        remove_assignee = { lhs = '<leader>iar', desc = 'remove assignee' },
        create_label = { lhs = '<leader>ilc', desc = 'create label' },
        add_label = { lhs = '<leader>ila', desc = 'add label' },
        remove_label = { lhs = '<leader>ilr', desc = 'remove label' },
        goto_issue = { lhs = '<leader>igi', desc = 'navigate to a local repo issue' },
        add_comment = { lhs = '<leader>ic', desc = 'add comment' },
        delete_comment = { lhs = '<leader>id', desc = 'delete comment' },
        next_comment = { lhs = ']t', desc = 'go to next comment' },
        prev_comment = { lhs = '[t', desc = 'go to previous comment' },
        react_hooray = { lhs = '<leader>irp', desc = 'add/remove 🎉 reaction' },
        react_heart = { lhs = '<leader>irh', desc = 'add/remove ❤️ reaction' },
        react_eyes = { lhs = '<leader>ire', desc = 'add/remove 👀 reaction' },
        react_thumbs_up = { lhs = '<leader>ir+', desc = 'add/remove 👍 reaction' },
        react_thumbs_down = { lhs = '<leader>ir-', desc = 'add/remove 👎 reaction' },
        react_rocket = { lhs = '<leader>irr', desc = 'add/remove 🚀 reaction' },
        react_laugh = { lhs = '<leader>irl', desc = 'add/remove 😄 reaction' },
        react_confused = { lhs = '<leader>irc', desc = 'add/remove 😕 reaction' },
      },
      pull_request = {
        checkout_pr = { lhs = '<leader>pco', desc = 'checkout PR' },
        merge_pr = { lhs = '<leader>pm', desc = 'merge commit PR' },
        squash_and_merge_pr = { lhs = '<leader>psm', desc = 'squash and merge PR' },
        rebase_and_merge_pr = { lhs = '<leader>prm', desc = 'rebase and merge PR' },
        list_commits = { lhs = '<leader>pc', desc = 'list PR commits' },
        list_changed_files = { lhs = '<leader>pf', desc = 'list PR changed files' },
        show_pr_diff = { lhs = '<leader>pd', desc = 'show PR diff' },
        add_reviewer = { lhs = '<leader>pra', desc = 'add reviewer' },
        remove_reviewer = { lhs = '<leader>prr', desc = 'remove reviewer request' },
        close_issue = { lhs = '<leader>ic', desc = 'close PR' },
        reopen_issue = { lhs = '<leader>io', desc = 'reopen PR' },
        list_issues = { lhs = '<leader>il', desc = 'list open issues on same repo' },
        reload = { lhs = '<C-r>', desc = 'reload PR' },
        open_in_browser = { lhs = '<C-b>', desc = 'open PR in browser' },
        copy_url = { lhs = '<C-y>', desc = 'copy url to system clipboard' },
        add_assignee = { lhs = '<leader>iaa', desc = 'add assignee' },
        remove_assignee = { lhs = '<leader>iar', desc = 'remove assignee' },
        create_label = { lhs = '<leader>ilc', desc = 'create label' },
        add_label = { lhs = '<leader>ila', desc = 'add label' },
        remove_label = { lhs = '<leader>ilr', desc = 'remove label' },
        goto_issue = { lhs = '<leader>igi', desc = 'navigate to a local repo issue' },
        add_comment = { lhs = '<leader>ic', desc = 'add comment' },
        delete_comment = { lhs = '<leader>id', desc = 'delete comment' },
        next_comment = { lhs = ']t', desc = 'go to next comment' },
        prev_comment = { lhs = '[t', desc = 'go to previous comment' },
        react_hooray = { lhs = '<leader>irp', desc = 'add/remove 🎉 reaction' },
        react_heart = { lhs = '<leader>irh', desc = 'add/remove ❤️ reaction' },
        react_eyes = { lhs = '<leader>ire', desc = 'add/remove 👀 reaction' },
        react_thumbs_up = { lhs = '<leader>ir+', desc = 'add/remove 👍 reaction' },
        react_thumbs_down = { lhs = '<leader>ir-', desc = 'add/remove 👎 reaction' },
        react_rocket = { lhs = '<leader>irr', desc = 'add/remove 🚀 reaction' },
        react_laugh = { lhs = '<leader>irl', desc = 'add/remove 😄 reaction' },
        react_confused = { lhs = '<leader>irc', desc = 'add/remove 😕 reaction' },
      },
      review_thread = {
        goto_issue = { lhs = '<leader>igi', desc = 'navigate to a local repo issue' },
        add_comment = { lhs = '<leader>ic', desc = 'add comment' },
        add_suggestion = { lhs = '<leader>is', desc = 'add suggestion' },
        delete_comment = { lhs = '<leader>id', desc = 'delete comment' },
        next_comment = { lhs = ']t', desc = 'go to next comment' },
        prev_comment = { lhs = '[t', desc = 'go to previous comment' },
        select_next_entry = { lhs = ']q', desc = 'move to next file' },
        select_prev_entry = { lhs = '[q', desc = 'move to previous file' },
        react_hooray = { lhs = '<leader>irp', desc = 'add/remove 🎉 reaction' },
        react_heart = { lhs = '<leader>irh', desc = 'add/remove ❤️ reaction' },
        react_eyes = { lhs = '<leader>ire', desc = 'add/remove 👀 reaction' },
        react_thumbs_up = { lhs = '<leader>ir+', desc = 'add/remove 👍 reaction' },
        react_thumbs_down = { lhs = '<leader>ir-', desc = 'add/remove 👎 reaction' },
        react_rocket = { lhs = '<leader>irr', desc = 'add/remove 🚀 reaction' },
        react_laugh = { lhs = '<leader>irl', desc = 'add/remove 😄 reaction' },
        react_confused = { lhs = '<leader>irc', desc = 'add/remove 😕 reaction' },
        close_review_tab = { lhs = '<C-c>', desc = 'close review tab' },
      },
      submit_win = {
        approve_review = { lhs = '<C-a>', desc = 'approve review' },
        comment_review = { lhs = '<C-m>', desc = 'comment review' },
        request_changes = { lhs = '<C-r>', desc = 'request changes review' },
        close_review_tab = { lhs = '<C-c>', desc = 'close review tab' },
      },
      review_diff = {
        add_review_comment = { lhs = '<leader>ic', desc = 'add review comment' },
        add_review_suggestion = { lhs = '<leader>is', desc = 'add review suggestion' },
        focus_files = { lhs = '<leader>e', desc = 'move focus to changed file panel' },
        toggle_files = { lhs = '<leader>b', desc = 'hide/show changed files panel' },
        next_thread = { lhs = ']t', desc = 'move to next thread' },
        prev_thread = { lhs = '[t', desc = 'move to previous thread' },
      },
      file_panel = {
        next_entry = { lhs = 'j', desc = 'move to next entry' },
        prev_entry = { lhs = 'k', desc = 'move to previous entry' },
        select_entry = { lhs = 'o', desc = 'select entry' },
        refresh_files = { lhs = 'R', desc = 'refresh files' },
        focus_files = { lhs = '<leader>e', desc = 'move focus to changed file panel' },
        toggle_files = { lhs = '<leader>b', desc = 'hide/show changed files panel' },
      },
    },
  },
}
